name: Deploy Musai-AI (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ec2-user/musai-ai
            git fetch origin
            git checkout main
            git pull origin main

            docker stop musai-ai || true
            docker rm musai-ai || true
            docker rmi musai-ai || true

            docker build -t musai-ai .

            docker run -d \
            --name musai-ai \
            --network musai-network \
            -p 8000:8000 \
            -v /home/ec2-user/musai-ai/service_account.json:/app/service_account.json:ro \
            -e GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json \
            -e GEMINI_MODEL_NAME=gemini-2.5 \
            musai-ai


